In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [7]:
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import make_pipeline
from sklearn.ensemble import VotingRegressor
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder


In [3]:
df=sns.load_dataset('tips')

In [4]:
df


total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [8]:
df.isnull().mean()*100


total_bill    0.0
tip           0.0
sex           0.0
smoker        0.0
day           0.0
time          0.0
size          0.0
dtype: float64

In [10]:
x=df[['sex','smoker','day','time']]

for i in x:
    le=LabelEncoder()
    x[i]=le.fit_transform(x[i])

<ipython-input-10-f4005d5b201a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i]=le.fit_transform(x[i])
<ipython-input-10-f4005d5b201a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x[i]=le.fit_transform(x[i])
<ipython-input-10-f4005d5b201a>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#re

In [12]:
df[['sex','smoker','day','time']]=x

In [13]:
df

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]

In [16]:
x=df.drop('total_bill',axis=1)
y=df['total_bill']

In [17]:
xtr,xte,ytr,yte=train_test_split(x,y,test_size=0.2,random_state=42)

In [47]:
clf1=LinearRegression()
clf2=DecisionTreeRegressor(splitter='best',max_depth=3)
clf3=RandomForestRegressor(max_depth=4,n_estimators=80)

In [48]:
est=[('lr',clf1),('dt',clf2),('rf',clf3)]

In [51]:
for estimators in est:

  cross=cross_val_score(estimators[1],xtr,ytr,cv=10)
  print(estimators[0],np.round(cross.mean(),2))

lr 0.48
dt 0.41
rf 0.42


In [71]:
#now giving the weignth
for i in range (1,4):
  for j in range (1,4):
    for k in range (1,4):
      vr=VotingRegressor(estimators=est,weights=[i,j,k])
      cross=cross_val_score(vr,xtr,ytr,scoring='r2',cv=10)
      print(f"for i={i}, j={j}, k={k} -> Avg R²:", np.round(np.mean(cross), 2))

for i=1, j=1, k=1 -> Avg R²: 0.474
for i=1, j=1, k=2 -> Avg R²: 0.461
for i=1, j=1, k=3 -> Avg R²: 0.454
for i=1, j=2, k=1 -> Avg R²: 0.465
for i=1, j=2, k=2 -> Avg R²: 0.46
for i=1, j=2, k=3 -> Avg R²: 0.461
for i=1, j=3, k=1 -> Avg R²: 0.46
for i=1, j=3, k=2 -> Avg R²: 0.458
for i=1, j=3, k=3 -> Avg R²: 0.458
for i=2, j=1, k=1 -> Avg R²: 0.483
for i=2, j=1, k=2 -> Avg R²: 0.473
for i=2, j=1, k=3 -> Avg R²: 0.469
for i=2, j=2, k=1 -> Avg R²: 0.477
for i=2, j=2, k=2 -> Avg R²: 0.476
for i=2, j=2, k=3 -> Avg R²: 0.469
for i=2, j=3, k=1 -> Avg R²: 0.473
for i=2, j=3, k=2 -> Avg R²: 0.468
for i=2, j=3, k=3 -> Avg R²: 0.464
for i=3, j=1, k=1 -> Avg R²: 0.486
for i=3, j=1, k=2 -> Avg R²: 0.478
for i=3, j=1, k=3 -> Avg R²: 0.475
for i=3, j=2, k=1 -> Avg R²: 0.485
for i=3, j=2, k=2 -> Avg R²: 0.481
for i=3, j=2, k=3 -> Avg R²: 0.469
for i=3, j=3, k=1 -> Avg R²: 0.481
for i=3, j=3, k=2 -> Avg R²: 0.473
for i=3, j=3, k=3 -> Avg R²: 0.475


In [ ]:
vr=VotingRegressor(estimators=est)

In [72]:
vr1=VotingRegressor(estimators=est,weights=[3,1,1])

In [53]:
cross=cross_val_score(vr,xtr,ytr,scoring='r2',cv=10)
print("Voting regressor",np.round(np.mean(cross),2))

Voting regressor 0.47


In [73]:
cross=cross_val_score(vr1,xtr,ytr,scoring='r2',cv=10)
print("Voting regressor",np.round(np.mean(cross),2))

Voting regressor 0.48


In [54]:
z=vr.fit(xtr,ytr)

In [74]:
z1=vr1.fit(xtr,ytr)

In [55]:
predict=vr.predict(xte)


In [76]:
predict1=vr1.predict(xte)

In [56]:
r2=r2_score(yte,predict)
print(r2)

0.5865214379494309


In [77]:
r21=r2_score(yte,predict1)
print(r21)

0.6118762965985112


In [78]:
input_string = input("enter all values for the prediction: ")


arr_str = input_string.split()

arr_np = np.array(arr_str, dtype=float)
arr=arr_np.reshape(1,-1)
arr

enter all values for the prediction: 1 1 1  2 3


array([[1., 1., 1., 2., 3.]])

In [59]:
arr

array([[1., 1., 1., 2., 1., 3.]])

In [60]:
vr.predict(arr)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([21.52820341])

In [61]:
pipe=make_pipeline(vr,est,z,predict)

In [66]:
print(pipe)

Pipeline(steps=[('votingregressor-1',
                 VotingRegressor(estimators=[('lr', LinearRegression()),
                                             ('dt',
                                              DecisionTreeRegressor(max_depth=3)),
                                             ('rf',
                                              RandomForestRegressor(max_depth=4,
                                                                    n_estimators=80))])),
                ('list',
                 [('lr', LinearRegression()),
                  ('dt', DecisionTreeRegressor(max_depth=3)),
                  ('rf', RandomForestRegressor(max_depth=4, n_estimators=80))]),
                ('votingregressor-2...
       18.16851084, 24.12749288, 19.94386816, 14.91077035, 30.19991772,
       22.48896227, 22.2059261 , 21.65797684, 13.74789304, 24.80058198,
       14.06799906, 14.17338957, 23.23176533, 22.06299386, 31.93505281,
       23.66793941, 14.68406636, 22.3362507 , 21.96013916, 22.